# ─────────────────────────────────────────────────────────
# 사이트 정보
# ─────────────────────────────────────────────────────────
title: "Hyun Yeol Cho — Dev Blog"
description: "Full-stack projects, AI/ML notes, and career journal"
url: "https://daniel972632.github.io"
baseurl: ""   # 사용자/organization 페이지면 빈 문자열

# ─────────────────────────────────────────────────────────
# 언어/시간대
# ─────────────────────────────────────────────────────────
lang: "ko-KR"
timezone: "Asia/Seoul"

# ─────────────────────────────────────────────────────────
# 연락처 & 작성자
# ─────────────────────────────────────────────────────────
email: "daniel972632@kakao.com"
author: "Hyun Yeol Cho"

# ─────────────────────────────────────────────────────────
# 테마 & 소셜 링크
# ─────────────────────────────────────────────────────────
theme: minima
minima:
  skin: dark   # light | dark | auto
  social_links:
    - { platform: github,    user_url: "https://github.com/daniel972632" }
    - { platform: instagram, user_url: "https://www.instagram.com/121579x8" }
    - { platform: youtube,   user_url: "https://www.youtube.com/@조현열-l7m" }

# ─────────────────────────────────────────────────────────
# 네비게이션(상단 메뉴)
# ─────────────────────────────────────────────────────────
header_pages:
  - index.md
  - about.md
  - projects.md
  - posts.md

# ─────────────────────────────────────────────────────────
# 마크다운/하이라이트
# ─────────────────────────────────────────────────────────
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
highlighter: rouge

# ─────────────────────────────────────────────────────────
# 플러그인
#  (Gemfile에 jekyll-feed / jekyll-seo-tag / jekyll-sitemap 추가되어 있어야 함)
# ─────────────────────────────────────────────────────────
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# ─────────────────────────────────────────────────────────
# URL 규칙(포스트)
#  예: /posts/2025/08/18/my-post/
# ─────────────────────────────────────────────────────────
permalink: /posts/:year/:month/:day/:title/

# ─────────────────────────────────────────────────────────
# 기본값(선택) — 포스트에 layout 기본값 부여
# ─────────────────────────────────────────────────────────
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: false

# ─────────────────────────────────────────────────────────
# 옵션(필요 시 주석 해제)
# ─────────────────────────────────────────────────────────
# show_excerpts: true          # 홈에서 글 요약 보여주기
# paginate: 5                  # jekyll-paginate 사용 시
# google_analytics: G-XXXXXXX  # GA4 연결 시

# 태그/카테고리 아카이브가 필요하면 아래를 쓰고 Gemfile에 jekyll-archives 추가
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archives_category
#     tag: archives_tag
#   permalinks:
#     category: /category/:name/
#     tag: /tag/:name/
